package com.tjcu.bean;

import java.util.Date;

public class DetailContent {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETAIL_CONTENT.ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETAIL_CONTENT.TYPE_DETAIL_ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    private Integer typeDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETAIL_CONTENT.CONTENT
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETAIL_CONTENT.VIDEO_URL
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETAIL_CONTENT.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETAIL_CONTENT.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETAIL_CONTENT.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    private Date updateTime;

    @Override
    public String toString() {
        return "DetailContent{" +
                "id=" + id +
                ", typeDetailId=" + typeDetailId +
                ", content='" + content + '\'' +
                ", videoUrl='" + videoUrl + '\'' +
                ", createTime=" + createTime +
                ", updateId='" + updateId + '\'' +
                ", updateTime=" + updateTime +
                ", delFlag=" + delFlag +
                ", photopath='" + photopath + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DETAIL_CONTENT.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    private Integer delFlag;

    private String photopath;

    private String title;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPhotopath() {
        return photopath;
    }

    public void setPhotopath(String photopath) {
        this.photopath = photopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETAIL_CONTENT.ID
     *
     * @return the value of DETAIL_CONTENT.ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETAIL_CONTENT.ID
     *
     * @param id the value for DETAIL_CONTENT.ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETAIL_CONTENT.TYPE_DETAIL_ID
     *
     * @return the value of DETAIL_CONTENT.TYPE_DETAIL_ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public Integer getTypeDetailId() {
        return typeDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETAIL_CONTENT.TYPE_DETAIL_ID
     *
     * @param typeDetailId the value for DETAIL_CONTENT.TYPE_DETAIL_ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public void setTypeDetailId(Integer typeDetailId) {
        this.typeDetailId = typeDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETAIL_CONTENT.CONTENT
     *
     * @return the value of DETAIL_CONTENT.CONTENT
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETAIL_CONTENT.CONTENT
     *
     * @param content the value for DETAIL_CONTENT.CONTENT
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETAIL_CONTENT.VIDEO_URL
     *
     * @return the value of DETAIL_CONTENT.VIDEO_URL
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETAIL_CONTENT.VIDEO_URL
     *
     * @param videoUrl the value for DETAIL_CONTENT.VIDEO_URL
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETAIL_CONTENT.CREATE_TIME
     *
     * @return the value of DETAIL_CONTENT.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETAIL_CONTENT.CREATE_TIME
     *
     * @param createTime the value for DETAIL_CONTENT.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETAIL_CONTENT.UPDATE_ID
     *
     * @return the value of DETAIL_CONTENT.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETAIL_CONTENT.UPDATE_ID
     *
     * @param updateId the value for DETAIL_CONTENT.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETAIL_CONTENT.UPDATE_TIME
     *
     * @return the value of DETAIL_CONTENT.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETAIL_CONTENT.UPDATE_TIME
     *
     * @param updateTime the value for DETAIL_CONTENT.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DETAIL_CONTENT.DEL_FLAG
     *
     * @return the value of DETAIL_CONTENT.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DETAIL_CONTENT.DEL_FLAG
     *
     * @param delFlag the value for DETAIL_CONTENT.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:55:46 GMT+08:00 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}