package com.tjcu.bean;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.ID
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.TITLE
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.CONTENT
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NEWS.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    private Integer delFlag;

    private String photopath;

    public String getPhotopath() {
        return photopath;
    }

    public void setPhotopath(String photopath) {
        this.photopath = photopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.ID
     *
     * @return the value of NEWS.ID
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.ID
     *
     * @param id the value for NEWS.ID
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.TITLE
     *
     * @return the value of NEWS.TITLE
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.TITLE
     *
     * @param title the value for NEWS.TITLE
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.CONTENT
     *
     * @return the value of NEWS.CONTENT
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.CONTENT
     *
     * @param content the value for NEWS.CONTENT
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.CREATE_TIME
     *
     * @return the value of NEWS.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.CREATE_TIME
     *
     * @param createTime the value for NEWS.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.UPDATE_ID
     *
     * @return the value of NEWS.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.UPDATE_ID
     *
     * @param updateId the value for NEWS.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.UPDATE_TIME
     *
     * @return the value of NEWS.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.UPDATE_TIME
     *
     * @param updateTime the value for NEWS.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NEWS.DEL_FLAG
     *
     * @return the value of NEWS.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NEWS.DEL_FLAG
     *
     * @param delFlag the value for NEWS.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}