package com.tjcu.bean;

import java.util.Date;

public class TypeDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.TYPE_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.TYPE_TITLE
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private String typeTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.CONTENT_TITLE
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private String contentTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.CONTENT_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private Integer contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TYPE_DETAIL.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.ID
     *
     * @return the value of TYPE_DETAIL.ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.ID
     *
     * @param id the value for TYPE_DETAIL.ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.TYPE_ID
     *
     * @return the value of TYPE_DETAIL.TYPE_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.TYPE_ID
     *
     * @param typeId the value for TYPE_DETAIL.TYPE_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.TYPE_TITLE
     *
     * @return the value of TYPE_DETAIL.TYPE_TITLE
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public String getTypeTitle() {
        return typeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.TYPE_TITLE
     *
     * @param typeTitle the value for TYPE_DETAIL.TYPE_TITLE
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setTypeTitle(String typeTitle) {
        this.typeTitle = typeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.CONTENT_TITLE
     *
     * @return the value of TYPE_DETAIL.CONTENT_TITLE
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public String getContentTitle() {
        return contentTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.CONTENT_TITLE
     *
     * @param contentTitle the value for TYPE_DETAIL.CONTENT_TITLE
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setContentTitle(String contentTitle) {
        this.contentTitle = contentTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.CONTENT_ID
     *
     * @return the value of TYPE_DETAIL.CONTENT_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.CONTENT_ID
     *
     * @param contentId the value for TYPE_DETAIL.CONTENT_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.CREATE_TIME
     *
     * @return the value of TYPE_DETAIL.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.CREATE_TIME
     *
     * @param createTime the value for TYPE_DETAIL.CREATE_TIME
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.UPDATE_ID
     *
     * @return the value of TYPE_DETAIL.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.UPDATE_ID
     *
     * @param updateId the value for TYPE_DETAIL.UPDATE_ID
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.UPDATE_TIME
     *
     * @return the value of TYPE_DETAIL.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.UPDATE_TIME
     *
     * @param updateTime the value for TYPE_DETAIL.UPDATE_TIME
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TYPE_DETAIL.DEL_FLAG
     *
     * @return the value of TYPE_DETAIL.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TYPE_DETAIL.DEL_FLAG
     *
     * @param delFlag the value for TYPE_DETAIL.DEL_FLAG
     *
     * @mbg.generated Mon May 11 21:59:34 GMT+08:00 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}