package com.tjcu.adddao;

import com.tjcu.bean.News;
import com.tjcu.bean.NewsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NewsRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    long countByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    int deleteByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    List<News> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    News selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbg.generated Mon May 11 21:58:28 GMT+08:00 2020
     */
    int updateByPrimaryKey(News record);
}